---
# On deploie l'application python Portfolio V2
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-v2-deployment
  labels:
    app: portfolio-v2
spec: 
  replicas: {{replicas}}
  selector:
    matchLabels:
      app: portfilio-v2-app
  template:
    metadata:
      labels:
        app: portfolio-v2-template
    spec:
      containers:
        - name: portfolio-v2-app
          image: georgesmomo/portfolio-python-v2:latest
          imagePullPolicy: Alway
          env:
            - name: ENVIRONMENT
              value: "production"
            - name: DB_HOST
              value: "portfolio-v2-mysql-service"
            - name: DB_USER
              value: "portfolio_user"
            - name: DB_PASS
              value: "portfolio_pass"
            - name: DB_NAME
              value: "portfolio_db"
          resources:
            requests:
              cpu: "100m" #100 milli core, 100/1000 = 0.1 core, = 10%core
              memory: "256Mi"
            limits:
              cpu: "500m"
              memoty: "500Mi"
          ports: 
            - containerPort: 5000

---
# service de l'application
apiVersion: v1
kind: Service
metadata: 
  name: portfolio-v2-mysql-service
spec:
  type: NodePort
  selector:
    app: portfolio-v2-app
  ports:
    - protocol: TCP
      port: 5000 # port du service
      targetPort: 5000 # port du container, le port qu'on cible
      nodePort: {{nodeport}}
---

apiVersion: apps/v1
kind: Deployment
metadata: 
  name: portfolio-v2-mysql-deployment
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: portfolio-v2-mysql
  template:
    metadata:
      labels: 
        app: portfolio-v2-mysql
    spec:
      containers:
        - name: portfolio-v2-mysql
          image: mysql:5.7
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "rootpass"
            - name: MYSQL_DATABASE
              value: "portfolio_db"
            - name: MYSQL_USER
              value: "portfolio_user"
            - name: MYSQL_PASSWORD
              value: "portfolio_pass" 
          ports:
            - containerPort: 3306

---
# le service de la base de données mysql
apiVersion: v1
kind: Service
metadata:
  name: portfolio-v2-mysql-service
spec: 
  selector:
    app: portfolio-v2-mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
