---
- name: Déploiement de l'application portfolio sur Kubernetes
  hosts: master
  become: false     # On n'utilise pas sudo ici car l'utilisateur jenkins a déjà les droits nécessaires
  tasks:
    - name: Copier le fichier de déploiement sur le master
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/../k8s/deployment.yaml"   # Chemin relatif vers le fichier de déploiement dans le repo
        dest: "/tmp/deployment.yaml"
      # Cette tâche copie le fichier de déploiement dans /tmp sur le serveur master

    - name: Appliquer la configuration de déploiement sur Kubernetes
      ansible.builtin.shell: |
        microk8s.kubectl apply -f /tmp/deployment.yaml

    # NOUVELLE TÂCHE AJOUTÉE CI-DESSOUS
    - name: Forcer le redeploiement de l'application
      ansible.builtin.shell: |
        microk8s.kubectl rollout restart deployment/portfolio-app
        
      #args:
      #  warn: false
      # Cette tâche exécute la commande kubectl pour déployer ou mettre à jour l'application sur Kubernetes
