---
- name: Déploiement de l'application Portfolio V2 sur Kubernetes via Ansible
  hosts: master
  become: false
  tasks:
    - name: Copie des fichier de deploiement sur le serveur distant {{ inventory_hostname }}
      copy:
        src: "{{ playbook_dir }}/../k8s/deployment_tmp.yaml"
        dest: "/tmp/deployment.yaml"

    - name: On deploie le Deployment Kubernetes
      shell:
        microk8s.kubectl apply -f /tmp/deployment.yaml

    - name: Restart et vérifie le déploiement Kubernetes
      ansible.builtin.shell: |
        microk8s.kubectl rollout restart deployment/portfolio-v2-deployment
        microk8s.kubectl rollout status deployment/portfolio-v2-deployment
      register: rollout_output
      failed_when: "'error' in rollout_output.stderr"
