---
- name: Déploiement de l'application Portfolio V2 sur Kubernetes via Ansible
  hosts: master
  become: false
  tasks:
    - name: Copie des fichier de deploiement sur le serveur distant {{ inventory_hostname }}
      copy:
        src: "{{ playbook_dir }}/../k8s/deployment_tmp.yaml"
        dest: "/tmp/deployment.yaml"

    - name: On deploie le Deployment Kubernetes
      shell:
        microk8s.kubectl apply -f /tmp/deployment.yaml

    - name: On force le redeploiement
      shell:
        microk8s.kubectl rollout restart deployment/portfolio-app-v2